x-api-template: &api-common
  image: matheusdph20/rinha01:59
  restart: on-failure
  environment:
    - ASPNETCORE_URLS=http://+:80
    - ConnectionStrings__RedisConnection=redis:6379
    - Processors__DefaultUrl=http://payment-processor-default:8080
    - Processors__FallbackUrl=http://payment-processor-fallback:8080
  networks:
    - rinha-net
    - payment-processor
  depends_on:
    - redis
  deploy:
    resources:
      limits:
        cpus: "0.675"
        memory: "125MB"
services:
  api01:
    <<: *api-common

  api02:
    <<: *api-common

  redis:
    image: redis:6-alpine
    container_name: redis
    hostname: redis
    networks:
      - rinha-net
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "60MB"
        
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-net
    depends_on:
      - api01
      - api02
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"
networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true