services:

  db:
    image: postgres:16.9
    environment:
      POSTGRES_DB: integration_dbname
      POSTGRES_USER: integration_username
      POSTGRES_PASSWORD: integration_pw
    ports:
      - "5432:5432"
    command: 'postgres -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=4MB'
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U integration_username -d integration_dbname" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"

  api01: &api
    image: javando/rinha-backend-payment-gateway:latest
    hostname: api01
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=integration_dbname
      - DB_USERNAME=integration_username
      - DB_PASSWORD=integration_pw
      - SERVER_PORT=8080
      - PAYMENTS_PROCESSOR_DEFAULT_URI=http://elb:9991/payments
      - PAYMENTS_PROCESSOR_FALLBACK_URI=http://nonono:9991/payments
    ports:
      - "8081:8080"
    networks:
      - backend
      - payment-processor
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "115MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  elb:
    image: haproxy:3.2.3
    ports:
      - "9999:9999"
      - "8404:8404"
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy
    depends_on:
      - api01
      - api02
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "20MB"
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 10s

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
